---
sudo: required

services:
  - docker

language: go
sudo: true
notifications:
  email: true
go:
  - "1.15.x"
env:
  global:
    - GO111MODULE=on
    - GO15VENDOREXPERIMENT=1
install:
  - make dev-dependencies
script:
  - make
  - make cover
  - make release
deploy:
  - provider: releases
    api_key:
      secure: "u1TVIguj4UCeHusQYByB+YANwSj1SzQgdf++8wLwKs3dDpLwbyB9DOMGMywjpRGy0P6qoAcipJyJeF2qb9O5rINAPPn2muuxmkUrm/gUTmK1OvQq6N+w7wfl7/ONOZ3fIQAyRChZ+O/7b7cfQyaxm8kyWV8sqA/Jyx9fQQez9bDiMzZhMvaKNCGA3DmobzdbK0GVOATOXeQfrybZ5gTnaRhfS8pR/NBZWVRRLqTkisT9/PzUFdPPEJS4lfxzHO+5AA9gXZxysz0rwz/skYxLaj+JERBkBAyl2mzxFcDS91v2sywnwpJD/WifrMouqmheitC08HVnlu+CFrqHN871SDRukwqrJasi8mtE9rIpoNMwKPQ43TQOSIjEnnnX2W5M8XqzuIhNyAtkQrCue3ryUKPDNXZytRjhqxPO64Zj+UGmjHk/xn24k4zQGGu/pTM4hziENLWQJFGquchwVNwgqoTX0bd/MmbMerqarfP7WXXqM0LAEfo6zx1/1wfBcHp/XMujoGzbE34Vmfzt4m/HYcaqfssqt5Kd6Z6SVgAVNqV1T5gd462l5x0py2SBybtF4m53IUhQZBOrdwxuBgDTVRr72EjFGe+JZ9ahdys6NazpW9nJ4Ywi+eyLLoUk6pXbJjuU2wR97HBJL6St59MNdFAKJBYxUMVRHxpCFXWBjXM="
    file:
      - build/dblock-linux-amd64.md5
      - build/dblock-linux-amd64.sha256
      - build/dblock-linux-amd64
      - build/dblock-linux-386.md5
      - build/dblock-linux-386.sha256
      - build/dblock-linux-386
      - build/dblock-linux-arm.md5
      - build/dblock-linux-arm.sha256
      - build/dblock-linux-arm
      - build/dblock-linux-arm64.md5
      - build/dblock-linux-arm64.sha256
      - build/dblock-linux-arm64
      - build/dblock-windows-amd64.md5
      - build/dblock-windows-amd64.sha256
      - build/dblock-windows-amd64
      - build/dblock-windows-386.md5
      - build/dblock-windows-386.sha256
      - build/dblock-windows-386
      - build/dblock-darwin-amd64.md5
      - build/dblock-darwin-amd64.sha256
      - build/dblock-darwin-amd64
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: bash deploy/deploy.sh
    on:
      tags: true
